#!/usr/bin/env bash
# pull-user.sh — Download a user's registry entry to config/users/<username>.env.
# The output file can be edited and passed back to ./admin.sh update-user.
#
# Usage: ./admin.sh pull-user <username>
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ---------------------------------------------------------------------------
# Load config
# ---------------------------------------------------------------------------
if [[ ! -f "${SCRIPT_DIR}/../config/admin.env" ]]; then
  echo "ERROR: config/admin.env not found." >&2
  exit 1
fi
source "${SCRIPT_DIR}/../config/admin.env"

if [[ ! -f "${SCRIPT_DIR}/../config/backend.env" ]]; then
  echo "ERROR: config/backend.env not found. Run './admin.sh bootstrap' first." >&2
  exit 1
fi
source "${SCRIPT_DIR}/../config/backend.env"

# shellcheck source=scripts/users-s3.sh
source "${SCRIPT_DIR}/users-s3.sh"

: "${PROJECT_NAME:?}" "${TF_BACKEND_BUCKET:?}" "${TF_BACKEND_REGION:?}"

# ---------------------------------------------------------------------------
# Resolve username
# ---------------------------------------------------------------------------
DEV_USERNAME="${DEV_USERNAME:-}"
if [[ -z "${DEV_USERNAME}" ]]; then
  echo "ERROR: DEV_USERNAME not set. Use './admin.sh pull-user <username>'." >&2
  exit 1
fi

# ---------------------------------------------------------------------------
# Export AWS credentials
# ---------------------------------------------------------------------------
_PROFILE_ARGS=()
[[ -n "${AWS_PROFILE:-}" ]] && _PROFILE_ARGS=(--profile "${AWS_PROFILE}")
_CREDS=$(aws configure export-credentials "${_PROFILE_ARGS[@]}" --format env-no-export 2>/dev/null) || {
  echo "ERROR: Could not export credentials${AWS_PROFILE:+ for profile '${AWS_PROFILE}'}." >&2
  echo "       Run './admin.sh sso-login' first." >&2
  exit 1
}
eval "$(echo "${_CREDS}" | sed 's/^/export /')"
unset _CREDS _PROFILE_ARGS

# ---------------------------------------------------------------------------
# Download registry
# ---------------------------------------------------------------------------
USERS_JSON=$(mktemp)
trap 'rm -f "${USERS_JSON}"' EXIT

users_s3_download "${USERS_JSON}"

if ! jq -e --arg u "${DEV_USERNAME}" '.[$u] != null' "${USERS_JSON}" >/dev/null 2>&1; then
  echo "ERROR: User '${DEV_USERNAME}' not found in registry." >&2
  exit 1
fi

# ---------------------------------------------------------------------------
# Extract fields
# ---------------------------------------------------------------------------
user_email=$(   jq -r --arg u "${DEV_USERNAME}" '.[$u].user_email        // ""'     "${USERS_JSON}")
role=$(         jq -r --arg u "${DEV_USERNAME}" '.[$u].role              // "user"' "${USERS_JSON}")
git_name=$(     jq -r --arg u "${DEV_USERNAME}" '.[$u].git_user_name     // ""'     "${USERS_JSON}")
git_email=$(    jq -r --arg u "${DEV_USERNAME}" '.[$u].git_user_email    // ""'     "${USERS_JSON}")
ssh_key=$(      jq -r --arg u "${DEV_USERNAME}" '.[$u].ssh_public_key    // ""'     "${USERS_JSON}")
pref_shell=$(   jq -r --arg u "${DEV_USERNAME}" '.[$u].preferred_shell   // "bash"' "${USERS_JSON}")

# Per-user compute overrides (empty = use project-wide default from admin.env)
instance_type=$(   jq -r --arg u "${DEV_USERNAME}" '.[$u].instance_type          // ""' "${USERS_JSON}")
use_spot=$(        jq -r --arg u "${DEV_USERNAME}" '.[$u].use_spot               // ""' "${USERS_JSON}")
hibernation=$(     jq -r --arg u "${DEV_USERNAME}" '.[$u].hibernation            // ""' "${USERS_JSON}")
data_volume_size=$(jq -r --arg u "${DEV_USERNAME}" '.[$u].ebs_data_volume_size_gb // ""' "${USERS_JSON}")

# ---------------------------------------------------------------------------
# Write output file
# ---------------------------------------------------------------------------
OUT_DIR="${SCRIPT_DIR}/../config/users"
mkdir -p "${OUT_DIR}"
OUT_FILE="${OUT_DIR}/${DEV_USERNAME}.env"

cat > "${OUT_FILE}" <<EOF
# fre-aws user registry entry — generated by pull-user on $(date -u +%Y-%m-%d)
# Edit the fields below, then run:
#   ./admin.sh update-user config/users/${DEV_USERNAME}.env
# To re-add from scratch (creates Identity Center user + installer bundle):
#   ./admin.sh add-user config/users/${DEV_USERNAME}.env
NEW_USERNAME=${DEV_USERNAME}
USER_EMAIL=${user_email}
ROLE=${role}
GIT_USER_NAME=${git_name}
GIT_USER_EMAIL=${git_email}
SSH_PUBLIC_KEY=${ssh_key}
PREFERRED_SHELL=${pref_shell}

# ---- Per-user compute overrides (leave empty to use the project-wide default) ----
# Changes here require a new instance — apply with: admin.sh migrate <username>
# Note: HIBERNATION=true requires USE_SPOT=false
INSTANCE_TYPE=${instance_type}
USE_SPOT=${use_spot}
HIBERNATION=${hibernation}
# Data volume size — expand only (never shrink). Apply with 'admin.sh up <username>',
# then run 'sudo resize2fs /dev/disk/by-label/fre-user-data' on the instance.
# No migration needed. Root volume size is fixed at the project default (EBS_VOLUME_SIZE_GB).
EBS_DATA_VOLUME_SIZE_GB=${data_volume_size}
EOF

echo "Registry entry for '${DEV_USERNAME}' written to: config/users/${DEV_USERNAME}.env"
